// <auto-generated />
using System;
using FlightReservationSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FlightReservationSystem.Migrations
{
    [DbContext(typeof(FlightReservation))]
    [Migration("20250525064142_FixAirportFKs")]
    partial class FixAirportFKs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MYAPPUSER")
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("AIRPLANES_SEQ");

            modelBuilder.HasSequence("AIRPORTS_SEQ");

            modelBuilder.HasSequence("BOOKED_TICKETS_SEQ");

            modelBuilder.HasSequence("BOOKINGS_SEQ");

            modelBuilder.HasSequence("FLIGHT_PRICES_SEQ");

            modelBuilder.HasSequence("FLIGHTS_SEQ");

            modelBuilder.HasSequence("PASSENGERS_SEQ");

            modelBuilder.HasSequence("REVIEWS_SEQ");

            modelBuilder.HasSequence("USERS_SEQ");

            modelBuilder.HasSequence("WALLET_TRANSACTIONS_SEQ");

            modelBuilder.HasSequence("WALLET_TX_SEQ");

            modelBuilder.HasSequence("WALLETS_SEQ");

            modelBuilder.Entity("FlightReservationSystem.Models.Airplanes", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("AIRPLANES_SEQ.NEXTVAL");

                    b.Property<string>("AirplaneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("AIRPLANE_NUMBER");

                    b.Property<decimal>("BusinessSeats")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("BUSINESS_SEATS");

                    b.Property<decimal>("EconomySeats")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ECONOMY_SEATS");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("MODEL");

                    b.Property<decimal>("TotalSeats")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TOTAL_SEATS");

                    b.HasKey("Id");

                    b.ToTable("AIRPLANES", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Airports", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("AIRPORTS_SEQ.NEXTVAL");

                    b.Property<string>("AirportCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NCHAR(3)")
                        .HasColumnName("AIRPORT_CODE")
                        .IsFixedLength();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CITY");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("COUNTRY");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("AIRPORTS", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.BookedTickets", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("BookingId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateTime?>("CancellationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("FlightClass")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("PassengerId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.ToTable("BookedTickets", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Bookings", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateTime?>("BookingTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("FlightId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Bookings", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.FlightPrices", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("FLIGHT_PRICES_SEQ.NEXTVAL");

                    b.Property<string>("FlightClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("FLIGHT_CLASS");

                    b.Property<decimal>("FlightId")
                        .HasColumnType("DECIMAL(10)")
                        .HasColumnName("FLIGHT_ID");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("PRICE");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("FLIGHT_PRICES", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Flights", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10)
                        .HasColumnType("DECIMAL(10)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("FLIGHTS_SEQ.NEXTVAL");

                    b.Property<decimal>("AirplaneId")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("AIRPLANE_ID");

                    b.Property<decimal?>("AirplanesId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal?>("AirportsId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal?>("AirportsId1")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ARRIVAL_TIME");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DEPARTURE_TIME");

                    b.Property<decimal>("DestinationAirportId")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("DESTINATION_AIRPORT_ID");

                    b.Property<string>("FlightName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FLIGHT_NAME");

                    b.Property<decimal>("SourceAirportId")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("SOURCE_AIRPORT_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id")
                        .HasName("SYS_C008287");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("AirplanesId");

                    b.HasIndex("AirportsId");

                    b.HasIndex("AirportsId1");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("SourceAirportId");

                    b.ToTable("FLIGHTS", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Passengers", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("AadhaarNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("Age")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("BookingId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Passengers", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Users", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("USERS_SEQ.NEXTVAL");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("DATE")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("GENDER");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("MOBILE_NUMBER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ROLE");

                    b.HasKey("Id");

                    b.ToTable("USERS", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.WalletTransactions", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("TransactionTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("WalletId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("WalletTransactions", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Wallets", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Wallets", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.BookedTickets", b =>
                {
                    b.HasOne("FlightReservationSystem.Models.Passengers", "Passenger")
                        .WithMany("BookedTickets")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.FlightPrices", b =>
                {
                    b.HasOne("FlightReservationSystem.Models.Flights", "Flight")
                        .WithMany("FlightPrices")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHT_PRICES_FLIGHTS");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Flights", b =>
                {
                    b.HasOne("FlightReservationSystem.Models.Airplanes", "Airplane")
                        .WithMany()
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHTS_AIRPLANE");

                    b.HasOne("FlightReservationSystem.Models.Airplanes", null)
                        .WithMany("Flights")
                        .HasForeignKey("AirplanesId");

                    b.HasOne("FlightReservationSystem.Models.Airports", null)
                        .WithMany("FlightsDestinationAirport")
                        .HasForeignKey("AirportsId");

                    b.HasOne("FlightReservationSystem.Models.Airports", null)
                        .WithMany("FlightsSourceAirport")
                        .HasForeignKey("AirportsId1");

                    b.HasOne("FlightReservationSystem.Models.Airports", "DestinationAirport")
                        .WithMany()
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHTS_DESTINATION_AIRPORT");

                    b.HasOne("FlightReservationSystem.Models.Airports", "SourceAirport")
                        .WithMany()
                        .HasForeignKey("SourceAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHTS_SOURCE_AIRPORT");

                    b.Navigation("Airplane");

                    b.Navigation("DestinationAirport");

                    b.Navigation("SourceAirport");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Airplanes", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Airports", b =>
                {
                    b.Navigation("FlightsDestinationAirport");

                    b.Navigation("FlightsSourceAirport");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Flights", b =>
                {
                    b.Navigation("FlightPrices");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Passengers", b =>
                {
                    b.Navigation("BookedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
