// <auto-generated />
using System;
using FlightReservationSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FlightReservationSystem.Migrations
{
    [DbContext(typeof(FlightReservation))]
    [Migration("20250527182052_UpdatedKeyTypes")]
    partial class UpdatedKeyTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MYAPPUSER")
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("AIRPLANES_SEQ");

            modelBuilder.HasSequence("AIRPORTS_SEQ");

            modelBuilder.HasSequence("BOOKED_TICKETS_SEQ");

            modelBuilder.HasSequence("BOOKINGS_SEQ");

            modelBuilder.HasSequence("FLIGHT_PRICES_SEQ");

            modelBuilder.HasSequence("FLIGHTS_SEQ");

            modelBuilder.HasSequence("PASSENGERS_SEQ");

            modelBuilder.HasSequence("REVIEWS_SEQ");

            modelBuilder.HasSequence("USERS_SEQ");

            modelBuilder.HasSequence("WALLET_TRANSACTIONS_SEQ");

            modelBuilder.HasSequence("WALLET_TX_SEQ");

            modelBuilder.HasSequence("WALLETS_SEQ");

            modelBuilder.HasSequence("WALLETTRANS_SEQ");

            modelBuilder.Entity("FlightReservationSystem.Models.Airplanes", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("AIRPLANES_SEQ.NEXTVAL");

                    b.Property<string>("AirplaneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("AIRPLANE_NUMBER");

                    b.Property<int>("BusinessSeats")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BUSINESS_SEATS");

                    b.Property<int>("EconomySeats")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ECONOMY_SEATS");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("MODEL");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TOTAL_SEATS");

                    b.HasKey("Id");

                    b.ToTable("AIRPLANES", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Airports", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("AIRPORTS_SEQ.NEXTVAL");

                    b.Property<string>("AirportCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("CHAR(3)")
                        .HasColumnName("AIRPORT_CODE")
                        .IsFixedLength();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CITY");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("COUNTRY");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("AIRPORTS", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.BookedTickets", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("BookingId")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("BOOKING_ID");

                    b.Property<DateTime?>("CancellationTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CANCELLATION_TIME");

                    b.Property<string>("FlightClass")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FLIGHT_CLASS");

                    b.Property<decimal>("PassengerId")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("PASSENGER_ID");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("PRICE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("BOOKED_TICKETS", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Bookings", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("BOOKING_TIME");

                    b.Property<decimal>("FlightId")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("FLIGHT_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("TOTAL_PRICE");

                    b.Property<decimal>("UserId")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.ToTable("BOOKINGS", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.FlightPrices", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("FLIGHT_PRICES_SEQ.NEXTVAL");

                    b.Property<string>("FlightClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("FLIGHT_CLASS");

                    b.Property<decimal>("FlightId")
                        .HasPrecision(18)
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("FLIGHT_ID");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("PRICE");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("FLIGHT_PRICES", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Flights", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10)
                        .HasColumnType("DECIMAL(10)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("FLIGHTS_SEQ.NEXTVAL");

                    b.Property<decimal?>("AirplaneId")
                        .HasPrecision(18)
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("AIRPLANE_ID");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ARRIVAL_TIME");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DEPARTURE_TIME");

                    b.Property<decimal?>("DestinationAirportId")
                        .HasPrecision(18)
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("DESTINATION_AIRPORT_ID");

                    b.Property<string>("FlightName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FLIGHT_NAME");

                    b.Property<decimal?>("SourceAirportId")
                        .HasPrecision(18)
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("SOURCE_AIRPORT_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("SourceAirportId");

                    b.ToTable("FLIGHTS", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Passengers", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("AadhaarNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("AADHAAR_NUMBER");

                    b.Property<int>("Age")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AGE");

                    b.Property<decimal>("BookingId")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("BOOKING_ID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("GENDER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LAST_NAME");

                    b.HasKey("Id");

                    b.ToTable("PASSENGERS", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Users", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("USERS_SEQ.NEXTVAL");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("DATE")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("GENDER");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("MOBILE_NUMBER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ROLE");

                    b.HasKey("Id");

                    b.ToTable("USERS", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.WalletTransaction", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("WALLETTRANS_SEQ.NEXTVAL");

                    b.Property<decimal>("Amount")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("AMOUNT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TRANSACTION_TYPE");

                    b.Property<decimal>("WalletId")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("WALLET_ID");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("WALLETTRANSACTIONS", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Wallets", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("WALLETS_SEQ.NEXTVAL");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("BALANCE");

                    b.Property<decimal>("UserId")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WALLETS", "MYAPPUSER");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.FlightPrices", b =>
                {
                    b.HasOne("FlightReservationSystem.Models.Flights", "Flight")
                        .WithMany("FlightPrices")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FLIGHT_PRICES_FLIGHTS");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Flights", b =>
                {
                    b.HasOne("FlightReservationSystem.Models.Airplanes", "Airplane")
                        .WithMany("Flights")
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_FLIGHTS_AIRPLANE");

                    b.HasOne("FlightReservationSystem.Models.Airports", "DestinationAirport")
                        .WithMany()
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_FLIGHTS_DESTINATION_AIRPORT");

                    b.HasOne("FlightReservationSystem.Models.Airports", "SourceAirport")
                        .WithMany()
                        .HasForeignKey("SourceAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_FLIGHTS_SOURCE_AIRPORT");

                    b.Navigation("Airplane");

                    b.Navigation("DestinationAirport");

                    b.Navigation("SourceAirport");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.WalletTransaction", b =>
                {
                    b.HasOne("FlightReservationSystem.Models.Wallets", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WALLETTRANSACTIONS_WALLETS");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Wallets", b =>
                {
                    b.HasOne("FlightReservationSystem.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WALLETS_USERS");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Airplanes", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("FlightReservationSystem.Models.Flights", b =>
                {
                    b.Navigation("FlightPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
